# WARNING : IF YOU BREAK THIS FILE YOU'LL BREAK THE WEBSITE. Tread carefully.
# Remember, you can test the website locally, see the README.


# The HTML metadata in the page header.
# Don't put double quotes (") in any of these fields.
meta:
    title: Pinkh4t
    keywords:
        - Python Developpement
        - Security
        - PinkHat
        - Forum
        - Sweet Community =)
    # Will be shown by search engines below the title of the page.
    # Will also be shown in the header if there's enough room
    description: An heliospheric propagation 1D MHD model for solar wind prediction at planets, probes and comets.

# The top bar
header:
    title: Welcome to Pinkhat
    links:
        - text: Logo
          href: "https://onlinelibrary.wiley.com/doi/10.1029/2004JA010959/abstract"
        - text: Horizon 2020
          href: "https://ec.europa.eu/programmes/horizon2020/"



# A list of authors that will appear in the HTML metadata and possibly in the
# authorship page as well. The order does not matter, it will be shuffled.
authors:
    - name: Miu
      role: Pink Nails
      mail: lagentillemiu@gmail.com
    - name: Goutte
      role: Pink Flexapunk
      mail: antoine@goutenoir.com

