# WARNING : IF YOU BREAK THIS FILE YOU'LL BREAK THE WEBSITE. Tread carefully.
# Remember, you can test the website locally, see the README.


# The HTML metadata in the page header.
# Don't put double quotes (") in any of these fields.
meta:
    title: Pinkh4t
    keywords:
        - Python Developpement
        - Security
        - PinkHat
        - Forum
        - Sweet Community =)
    # Will be shown by search engines below the title of the page.
    # Will also be shown in the header if there's enough room
    description: A new web Pinkhat Distrib learning platform! Our objectif ? Having fun !! Please leave us your suggestions for subjects, projects, games or whatever what you wanna see on this website.

# The top bar
header:
    title: "Welcome to Pinkhat"
    links:
        - text: "Logo"
         # href: "https://onlinelibrary.wiley.com/doi/10.1029/2004JA010959/abstract"
        - text: "Dont worry, Be pinky !"
         # href: "https://ec.europa.eu/programmes/horizon2020/"

# A list of authors that will appear in the HTML metadata and possibly in the
# authorship page as well. The order does not matter, it will be shuffled.
authors:
    - name: Pink MeowCoder
      mail: lagentillemiu@gmail.com
    - name: Pink Flexapunk
      mail: antoine@goutenoir.com
    - name: Pink Hvri
      mail: hvri.condor@gmail.com

# Navigation bar
# Change encoding utf-8 patching when start working on GNU/Linux <3
navigation:
  - title: "Bibliothèque"
    id: nav-biblio
    href: /biblio
    font: "fa fa-book"
  - title: "Flask & Jinja2"
    id: nav-flask
    href: /flask-jinja2
    font: "fa fa-heart"

# Icons
suggestion:
  title: Suggestion.txt
  id: icon-suggest
  href: /suggestion
