# WARNING : IF YOU BREAK THIS FILE YOU'LL BREAK THE WEBSITE. Tread carefully.
# Remember, you can test the website locally, see the README.


# The HTML metadata in the page header.
# Don't put double quotes (") in any of these fields.
meta:
    title: Pinkh4t
    keywords:
        - Python Developpement
        - Security
        - PinkHat
        - Forum
        - Sweet Community =)
    # Will be shown by search engines below the title of the page.
    # Will also be shown in the header if there's enough room
    description: A new web Pinkhat Distrib learning platform! Our objectif ? Having fun !! Please leave us your suggestions for subjects, projects, games or whatever what you wanna see on this website.

# The top bar
header:
    title: "Welcome to Pinkhat"
    links:
        - text: "Logo"
         # href: "https://onlinelibrary.wiley.com/doi/10.1029/2004JA010959/abstract"
        - text: "Dont worry, Be pinky !"
         # href: "https://ec.europa.eu/programmes/horizon2020/"

# A list of authors that will appear in the HTML metadata and possibly in the
# authorship page as well. The order does not matter, it will be shuffled.
authors:
    - name: Pink MeowCoder
      mail: lagentillemiu@gmail.com
    - name: Pink Flexapunk
      mail: antoine@goutenoir.com

# Navigation bar
navigation:
  - title: Biblioth&egrave;que
    id: nav-biblio
    href:
    children:
      - title: D&eacuteveloppement
        id: menu-dev
        href: /dev
      - title: S&eacutecurit&eacute num&eacuterique
        id: menu-secu
        href: /secu
      - title: Sensibilisation
        id: menu-sensi
        href: /sensi
      - title: Tutoriels
        id: menu-tuto
        href: /tuto
      - title: Lectures
        id: menu-read
        href: /lectures
  - title: "Projets"
    id: nav-proj
    href:
    children:
      - title: Sugg&eacuterez des projets !
        id: menu-proj
        href: /suggestion
  - title: "Jeux"
    id: nav-game
    href:
    children:
      - title: Sugg&eacuraterez des jeux !
        id: menu-game
        href: /suggestion


colors:
    Desktop background : 000000
    Navigation bar background : 310228
    Navigation bar hover : e258c8
    Navigation bar text : FFFFFF
    Very light pink: f8f3f6
    Very pinky pink: e43ac5
    Medium light pink: ed9bde