# WARNING : IF YOU BREAK THIS FILE YOU'LL BREAK THE WEBSITE. Tread carefully.
# Remember, you can test the website locally, see the README.


# The HTML metadata in the page header.
# Don't put double quotes (") in any of these fields.
meta:
    title: Pinkh4t
    keywords:
        - Python Developpement
        - Security
        - PinkHat
        - Forum
        - Sweet Community =)
    # Will be shown by search engines below the title of the page.
    # Will also be shown in the header if there's enough room
    description: A new web Pinkhat Distrib learning platform! Our objectif ? Having fun !! Please leave us your suggestions for subjects, projects, games or whatever what you wanna see on this website.

# The top bar
header:
    title: "Welcome to Pinkhat"
    links:
        - text: "Logo"
         # href: "https://onlinelibrary.wiley.com/doi/10.1029/2004JA010959/abstract"
        - text: "Dont worry, Be pinky !"
         # href: "https://ec.europa.eu/programmes/horizon2020/"

# A list of authors that will appear in the HTML metadata and possibly in the
# authorship page as well. The order does not matter, it will be shuffled.
authors:
    - name: Pink MeowCoder
      mail: lagentillemiu@gmail.com
    - name: Pink Flexapunk
      mail: antoine@goutenoir.com
    - name: Pink Hvri
      mail: hvri.condor@gmail.com

# Navigation bar
# Change encoding utf-8 patching when start working on GNU/Linux <3
navigation:
  - title: "Bibliothèque"
    id: nav-biblio
    href: /biblio
    children:
      - title: " Développement Web"
        id: menu-web
        href: /biblio/devweb
        font: "fa fa-code "
      - title: " Programmation"
        id: menu-prog
        href: /biblio/programmation
        font: "fa fa-coffee "
      - title: " Sécurité"
        id: menu-secu
        href: /biblio/securite
        font: "fa fa-lock "
      - title: " Sensibilisation"
        id: menu-sensi
        href: /biblio/sensibilisation
        font: "fa fa-bullhorn "
      - title: " Systèmes et Matériels"
        id: menu-sysm
        href: /biblio/sysm
        font: "fa fa-cogs "
      - title: " Tutoriels"
        id: menu-tuto
        href: /biblio/tutoriels
        font: "fa fa-pencil "
      - title: " Livres"
        id: menu-books
        href: /livres
        font: "fa fa-book "
  - title: "Projets"
    id: nav-proj
    href:
    children:
      - title: Suggérez des projets !
        id: menu-proj
        href: /suggestion
  - title: "Jeux"
    id: nav-game
    href:
    children:
      - title: Suggérez des jeux !
        id: menu-game
        href: /suggestion

# Icons
suggestion:
  title: Suggestion.txt
  id: icon-suggest
  href: /suggestion
