# WARNING : IF YOU BREAK THIS FILE YOU'LL BREAK THE WEBSITE. Tread carefully.
# Remember, you can test the website locally, see the README.


# The HTML metadata in the page header.
# Don't put double quotes (") in any of these fields.
meta:
    title: Pinkh4t
    keywords:
        - Python Developpement
        - Security
        - PinkHat
        - Forum
        - Sweet Community =)
    # Will be shown by search engines below the title of the page.
    # Will also be shown in the header if there's enough room
    description: A new web Pinkhat Distrib learning platform! Our objectif ? Having fun !! Please leave us your suggestions for subjects, projects, games or whatever what you wanna see on this website.

# The top bar
header:
    title: "Welcome to Pinkhat"
    links:
        - text: "Logo"
         # href: "https://onlinelibrary.wiley.com/doi/10.1029/2004JA010959/abstract"
        - text: "Dont worry, Be pinky !"
         # href: "https://ec.europa.eu/programmes/horizon2020/"

# A list of authors that will appear in the HTML metadata and possibly in the
# authorship page as well. The order does not matter, it will be shuffled.
authors:
    - name: Pink MeowCoder
      mail: lagentillemiu@gmail.com
    - name: Pink Flexapunk
      mail: antoine@goutenoir.com
    - name: Pink Hvri
      mail: hvri.condor@gmail.com

# Icons
icons:
  - title: Bibliothèque
    id: icon-biblio
    href: /bibliotheque
    font: "fa fa-book fa-3x "
  - title: Suggestion
    id: icon-suggest
    href: /suggestion
    font: "fa fa-file-text fa-3x "


#### Those icons are incoming :)
keyboard:
  title: " Ctrl + U "
  id: icon-keyboard

discord:
  title: Join us on discord :D
  id: icon-discord
  href:

twitter:
  title: Twit Twit
  id: icon-twit
  href:

github:
  title: follow us
  id: icon-github
  href:





colors:
    desktop-background : 000000
    nav-bar-backgroud : 310228
    nav-bar-hover : f8f3f6
    nav-bar-text : e258c8
    drop-down-menu-background: f8f3f6
    drop-down-menu-hover: 310228
    drop-down-menu-text: e258c8
    supp-one: e43ac5
    supp-two: ed9bde